### ISSUE TITLE
Client creds-style auth gives 401 when ran from firebase function

### ISSUE THREAD

**Issue by jabza** [thislooksfun/snoots#106]
### What happened?

When creating a Client with my Reddit app creds, it works from NodeJS REPL, but same code running inside firebase function gives 401.

It appears the app secret is not present in the password field of the request options.

### Reproduction steps

Create a new Client(userAgent: “something”, creds:{clientId: “cid”, secretId: “ckey”});

Making Reddit API requests works correctly from Node REPL, but not from Firebase function. (Ran locally OR hosted)

### Snoots Version

dev latest

### Node Version

v16

### Logs

```Shell
401 from got pkg.
```

**Comment by jabza** [comment]
I'm an idiot. The key is 'clientSecret' not 'secretId' - still I'm unsure why this worked locally!

**Comment by thislooksfun** [comment]
> still I'm unsure why this worked locally!

Ah, those are always the best bugs. Glad you got it fixed!
