### ISSUE TITLE
Docs page missing

### ISSUE THREAD

**Issue by nlanson** [thislooksfun/snoots#12]
Hello, 

In the documentation the link for step 3 is broken.
https://thislooks.fun/snoots/docs/latest/

Thanks

**Comment by thislooksfun** [comment]
Yeah there are definitely some broken links. It looks to me like the link in step 3 is the only one *not* broken though... odd.

**Comment by thislooksfun** [comment]
Alright it should be fixed over at https://thislooksfun/snoots/docs/master/. If it's still broken let me know. (/latest won't be fixed just yet, that's coming soon.)

**Comment by thislooksfun** [comment]
Alright, this should now be fixed everywhere.
