### ISSUE TITLE
Post.removed always undefined

### ISSUE THREAD

**Issue by thislooksfun** [thislooksfun/snoots#32]
Tracks progress towards #31.

**To Reproduce**
Post ID: `nmftww`

**Expected behavior**

**Comment by thislooksfun** [comment]
@messier102 fixed! It's a little bit of a hacky solution, so let me know if it seems wrong, but it should work!

**Comment by messier102** [comment]
Seems to be working for my purposes, thanks!

**Comment by thislooksfun** [comment]
Awesome! I should clarify (if only for posterity) that I am 99% sure this will not cause any false positives (posts marked as being removed when they weren't), but there's a decent chance of a false negative (posts marked as not being removed even though they were). If anyone has a better solution than the one in 4c7ba394b4c84e942879d26421c405bff9640966 I'm all ears, but until then this will stay.
