### ISSUE TITLE
Add dotenv and dotenv-expand as dependency for tests

### ISSUE THREAD

**Issue by JamesxX** [thislooksfun/snoots#92]
### The Problem
I can't write jest tests without including secrets in the file itself, meaning I can't commit working tests

### The Rationale
I'd like to start writing some tests for the features I've implemented (modnotes and wiki pages) and commit them to the repository, but I'm currently unable to do so as all my secrets are in the clear. By adding dotenv and dotenv-expand, a shared `.env` file could be added to the `.gitignore` file (updated as necessary for new tests). This will improve code coverage, and possibly allow test suites to be run on commit.

**Comment by JamesxX** [comment]
Added in #95

**Comment by thislooksfun** [comment]
Blocked by #11
